---
all:
  vars:
    ansible_user: cloud-user

kafka_controller:
  hosts:
    qa-controller-01.internal.net:
      node_id: 1
    qa-controller-02.internal.net:
      node_id: 2
    qa-controller-03.internal.net:
      node_id: 3

kafka_broker:
  hosts:
    qa-broker-01.internal.net:
      node_id: 101
    qa-broker-02.internal.net:
      node_id: 102
    qa-broker-03.internal.net:
      node_id: 103

schema_registry:
  hosts:
    qa-sr-01.internal.net:

kafka_connect:
  hosts:
    qa-connect-01.internal.net:
    qa-connect-02.internal.net:

kafka_rest:
  hosts:
    qa-rest-01.internal.net:
    qa-rest-02.internal.net:
