---
all:
  vars:
    ansible_user: cloud-user

kafka_controller:
  hosts:
    prod-dc1-ctrl-01.internal.net:
      node_id: 1
    prod-dc1-ctrl-02.internal.net:
      node_id: 2
    prod-dc2-ctrl-03.internal.net:
      node_id: 3

kafka_broker:
  hosts:
    prod-dc1-broker-01.internal.net:
      node_id: 101
      broker_rack: "dc1"
    prod-dc1-broker-02.internal.net:
      node_id: 102
      broker_rack: "dc1"
    prod-dc2-broker-03.internal.net:
      node_id: 103
      broker_rack: "dc2"
    prod-dc2-broker-04.internal.net:
      node_id: 104
      broker_rack: "dc2"

schema_registry:
  hosts:
    prod-dc1-sr-01.internal.net:
    prod-dc2-sr-02.internal.net:

kafka_connect:
  hosts:
    prod-dc1-connect-01.internal.net:
    prod-dc2-connect-02.internal.net:

kafka_rest:
  hosts:
    prod-dc1-rest-01.internal.net:
    prod-dc2-rest-02.internal.net:
