---
all:
  vars:
    ansible_user: cloud-user

kafka_controller:
  hosts:
    dr-ctrl-01.internal.net:
      node_id: 1
    dr-ctrl-02.internal.net:
      node_id: 2
    dr-ctrl-03.internal.net:
      node_id: 3

kafka_broker:
  hosts:
    dr-broker-01.internal.net:
      node_id: 101
      broker_rack: "dr"
    dr-broker-02.internal.net:
      node_id: 102
      broker_rack: "dr"
    dr-broker-03.internal.net:
      node_id: 103
      broker_rack: "dr"

schema_registry:
  hosts:
    dr-sr-01.internal.net:

kafka_connect:
  hosts:
    dr-connect-01.internal.net:

kafka_rest:
  hosts:
    dr-rest-01.internal.net:
