---
all:
  hosts:
    cp-node1:
      ansible_connection: local
    cp-node2:
      ansible_host: 10.0.0.2
      ansible_ssh_private_key_file: ~/.ssh/cp-node2.key
    cp-node3:
      ansible_host: 10.0.0.3
      ansible_ssh_private_key_file: ~/.ssh/cp-node3.key

kafka_controller:
  hosts:
    cp-node1:
      node_id: 1
    cp-node2:
      node_id: 2
    cp-node3:
      node_id: 3

kafka_broker:
  hosts:
    cp-node1:
      node_id: 1
    cp-node2:
      node_id: 2
    cp-node3:
      node_id: 3

schema_registry:
  hosts:
    cp-node1:
    cp-node2:
    cp-node3:

kafka_connect:
  hosts:
    cp-node1:
    cp-node2:
    cp-node3:

kafka_rest:
  hosts:
    cp-node1:
    cp-node2:
    cp-node3:

control_center_next_gen:
  hosts:
    cp-node3:
