---
all:
  vars:
    ansible_user: cloud-user

kafka_controller:
  hosts:
    dev-controller-01.internal.net:
      node_id: 1

kafka_broker:
  hosts:
    dev-broker-01.internal.net:
      node_id: 101
    dev-broker-02.internal.net:
      node_id: 102
    dev-broker-03.internal.net:
      node_id: 103

schema_registry:
  hosts:
    dev-sr-01.internal.net:

kafka_connect:
  hosts:
    dev-connect-01.internal.net:

kafka_rest:
  hosts:
    dev-rest-01.internal.net:
